"""
Linker script management for NexusLang bare-metal / freestanding builds.

This module handles:
  - Parsing and validating user-supplied linker scripts
  - Generating memory-region aware linker scripts from high-level descriptions
  - Invoking an external linker (ld, lld, arm-none-eabi-ld, etc.)
  - Producing build reports and symbol maps

This module is OPTIONAL and only used when building freestanding/bare-metal
firmware images.  It is not loaded during ordinary interpreter operation.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class MemoryRegion:
    """Describes a memory region for a linker script MEMORY block."""
    name: str
    origin: int
    length: int
    attributes: str = "rwx"  # r=read, w=write, x=execute, a=alloc, l=load

    @property
    def end(self) -> int:
        return self.origin + self.length

    def to_linker_script(self) -> str:
        attr = self.attributes.upper()
        return (f"    {self.name:<12} ({attr:<4}) : "
                f"ORIGIN = 0x{self.origin:08x}, "
                f"LENGTH = {self._fmt_length()}")

    def _fmt_length(self) -> str:
        if self.length % (1024 * 1024) == 0:
            return f"{self.length // (1024 * 1024)}M"
        if self.length % 1024 == 0:
            return f"{self.length // 1024}K"
        return str(self.length)


@dataclass
class LinkerSection:
    """Describes a section in the linker script SECTIONS block."""
    name: str
    load_region: str            # VMA region name
    run_region: Optional[str] = None   # LMA region name (for load-to-RAM copies)
    keep: bool = False
    patterns: List[str] = field(default_factory=lambda: ["*"])
    alignment: int = 4

    def to_linker_script(self, regions: Dict[str, MemoryRegion]) -> str:
        body_lines = []
        if self.alignment > 1:
            body_lines.append(f"        . = ALIGN({self.alignment});")
        if self.name == ".bss":
            body_lines.append("        __bss_start = .;")
        elif self.name == ".data":
            body_lines.append("        __data_load  = LOADADDR(.data);")
            body_lines.append("        __data_start = .;")

        for pat in self.patterns:
            inner = f"*({self.name}*)" if pat == "*" else f"{pat}({self.name}*)"
            if self.keep:
                inner = f"KEEP({inner})"
            body_lines.append(f"        {inner}")

        if self.name == ".bss":
            body_lines.append("        *(COMMON)")
            body_lines.append("        __bss_end = .;")
        elif self.name == ".data":
            body_lines.append("        __data_end = .;")

        at_clause = f" AT > {self.run_region}" if self.run_region else ""
        no_load = " (NOLOAD)" if self.name in (".bss", ".noinit") else ""
        body = "\n".join(body_lines)
        return (f"    {self.name}{no_load} : {{\n{body}\n    }}"
                f" > {self.load_region}{at_clause}")


@dataclass
class LinkerScriptConfig:
    """High-level description of the final linker script to be generated."""
    entry_symbol: str = "_start"
    regions: List[MemoryRegion] = field(default_factory=list)
    sections: List[LinkerSection] = field(default_factory=list)
    extra_symbols: Dict[str, str] = field(default_factory=dict)

    def add_region(self, name: str, origin: int, length: int,
                   attributes: str = "rwx") -> "LinkerScriptConfig":
        self.regions.append(MemoryRegion(name, origin, length, attributes))
        return self

    def add_section(self, name: str, load_region: str,
                    run_region: Optional[str] = None,
                    keep: bool = False,
                    alignment: int = 4) -> "LinkerScriptConfig":
        self.sections.append(LinkerSection(name, load_region, run_region, keep,
                                           alignment=alignment))
        return self

    def generate(self) -> str:
        """Generate the full linker script text from this configuration."""
        lines: List[str] = []
        lines.append(f"/* Generated by NexusLang bare-metal linker helper */")
        lines.append(f"ENTRY({self.entry_symbol})")
        lines.append("")
        lines.append("MEMORY")
        lines.append("{")
        regions_by_name = {}
        for r in self.regions:
            lines.append(r.to_linker_script())
            regions_by_name[r.name] = r
        lines.append("}")
        lines.append("")
        lines.append("SECTIONS")
        lines.append("{")
        for s in self.sections:
            lines.append(s.to_linker_script(regions_by_name))
        # Stack top symbol derived from last RAM region
        ram_regions = [r for r in self.regions if "w" in r.attributes.lower()]
        if ram_regions:
            last_ram = ram_regions[-1]
            lines.append(f"    __stack_top = ORIGIN({last_ram.name}) + LENGTH({last_ram.name});")
        # Extra user symbols
        for sym, expr in self.extra_symbols.items():
            lines.append(f"    {sym} = {expr};")
        lines.append("}")
        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Linker script presets
# ---------------------------------------------------------------------------

def cortex_m_config(flash_origin: int = 0x08000000,
                    flash_size: int = 256 * 1024,
                    sram_origin: int = 0x20000000,
                    sram_size: int = 64 * 1024) -> LinkerScriptConfig:
    """Return a pre-configured LinkerScriptConfig for ARM Cortex-M targets."""
    cfg = LinkerScriptConfig(entry_symbol="Reset_Handler")
    cfg.add_region("FLASH", flash_origin, flash_size, "rx")
    cfg.add_region("SRAM",  sram_origin,  sram_size,  "rwx")
    cfg.add_section(".vectors",  "FLASH", keep=True)
    cfg.add_section(".text",     "FLASH")
    cfg.add_section(".rodata",   "FLASH")
    cfg.add_section(".data",     "SRAM", run_region="FLASH")
    cfg.add_section(".bss",      "SRAM")
    return cfg


def x86_flat_config(rom_origin: int = 0x00100000,
                    rom_size: int = 512 * 1024,
                    ram_origin: int = 0x00200000,
                    ram_size: int = 256 * 1024) -> LinkerScriptConfig:
    """Return a pre-configured LinkerScriptConfig for x86 flat-binary targets."""
    cfg = LinkerScriptConfig(entry_symbol="_start")
    cfg.add_region("ROM", rom_origin, rom_size, "rx")
    cfg.add_region("RAM", ram_origin, ram_size, "rwx")
    cfg.add_section(".text",   "ROM")
    cfg.add_section(".rodata", "ROM")
    cfg.add_section(".data",   "RAM", run_region="ROM")
    cfg.add_section(".bss",    "RAM")
    return cfg


def riscv_config(flash_origin: int = 0x20010000,
                 flash_size: int = 512 * 1024,
                 sram_origin: int = 0x80000000,
                 sram_size: int = 16 * 1024) -> LinkerScriptConfig:
    """Return a pre-configured LinkerScriptConfig for RISC-V targets."""
    cfg = LinkerScriptConfig(entry_symbol="_start")
    cfg.add_region("FLASH", flash_origin, flash_size, "rx")
    cfg.add_region("SRAM",  sram_origin,  sram_size,  "rwx")
    cfg.add_section(".text.start", "FLASH", keep=True)
    cfg.add_section(".text",       "FLASH")
    cfg.add_section(".rodata",     "FLASH")
    cfg.add_section(".data",       "SRAM", run_region="FLASH")
    cfg.add_section(".bss",        "SRAM")
    return cfg


LINKER_PRESETS: Dict[str, Any] = {
    "cortex-m": cortex_m_config,
    "arm":      cortex_m_config,
    "x86":      x86_flat_config,
    "x86_64":   x86_flat_config,
    "riscv":    riscv_config,
    "riscv32":  riscv_config,
    "riscv64":  riscv_config,
}


def get_linker_script_for_arch(arch: str) -> str:
    """Return a generated linker script string for the given architecture."""
    key = arch.lower()
    if key not in LINKER_PRESETS:
        raise ValueError(
            f"linker: no preset for architecture '{arch}'. "
            f"Supported: {', '.join(sorted(LINKER_PRESETS))}"
        )
    cfg = LINKER_PRESETS[key]()
    return cfg.generate()


# ---------------------------------------------------------------------------
# Linker invocation
# ---------------------------------------------------------------------------

@dataclass
class LinkerInvocationResult:
    success: bool
    returncode: int
    stdout: str
    stderr: str
    output_file: Optional[str] = None
    map_file: Optional[str] = None


def find_linker(preferred: Optional[str] = None,
                arch: Optional[str] = None) -> Optional[str]:
    """Find a suitable linker binary on PATH.

    Looks for the preferred name first, then arch-prefixed linkers, then ld/lld.
    """
    candidates: List[str] = []
    if preferred:
        candidates.append(preferred)
    if arch:
        arch_lower = arch.lower()
        if "arm" in arch_lower or "cortex" in arch_lower:
            candidates += ["arm-none-eabi-ld", "arm-linux-gnueabi-ld"]
        elif "riscv" in arch_lower:
            candidates += ["riscv64-unknown-elf-ld", "riscv32-unknown-elf-ld"]
        elif "x86_64" in arch_lower:
            candidates += ["ld.lld", "ld"]
        else:
            candidates += ["ld.lld", "ld"]
    candidates += ["ld.lld", "ld"]

    for name in candidates:
        path = shutil.which(name)
        if path:
            return path
    return None


def invoke_linker(
    object_files: List[str],
    output_file: str,
    linker_script_path: Optional[str] = None,
    linker_binary: Optional[str] = None,
    arch: Optional[str] = None,
    extra_flags: Optional[List[str]] = None,
    generate_map: bool = True,
    verbose: bool = False,
) -> LinkerInvocationResult:
    """Invoke an external linker to produce a firmware binary.

    object_files     : list of .o / .a file paths to link
    output_file      : desired output path (e.g., firmware.elf)
    linker_script_path : path to the .ld linker script (optional)
    linker_binary    : explicit linker path; auto-detected if None
    arch             : architecture hint used for linker auto-detection
    extra_flags      : additional flags to pass to the linker
    generate_map     : emit a .map symbol file alongside the output
    verbose          : print the command before running

    Returns a LinkerInvocationResult with success status and output.
    """
    ld = linker_binary or find_linker(arch=arch)
    if ld is None:
        return LinkerInvocationResult(
            success=False, returncode=127, stdout="",
            stderr="linker: no linker binary found on PATH. "
                   "Install 'binutils' or pass --linker-binary."
        )

    cmd: List[str] = [ld]
    for obj in object_files:
        cmd.append(obj)
    cmd += ["-o", output_file]
    if linker_script_path:
        cmd += ["-T", linker_script_path]
    if generate_map:
        map_file = output_file + ".map"
        cmd += [f"--Map={map_file}"]
    else:
        map_file = None
    if extra_flags:
        cmd += extra_flags

    if verbose:
        print(" ".join(cmd))

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        success = result.returncode == 0
        return LinkerInvocationResult(
            success=success,
            returncode=result.returncode,
            stdout=result.stdout,
            stderr=result.stderr,
            output_file=output_file if success else None,
            map_file=map_file if success and generate_map else None,
        )
    except FileNotFoundError as e:
        return LinkerInvocationResult(
            success=False, returncode=127, stdout="",
            stderr=f"linker: binary not found: {e}"
        )
    except Exception as e:
        return LinkerInvocationResult(
            success=False, returncode=1, stdout="",
            stderr=f"linker: unexpected error: {e}"
        )


# ---------------------------------------------------------------------------
# Linker script parser (validates user-supplied scripts)
# ---------------------------------------------------------------------------

class LinkerScriptValidator:
    """Performs basic sanity checks on a user-supplied linker script."""

    # Patterns we actively look for
    _RE_ENTRY   = re.compile(r"\bENTRY\s*\(", re.IGNORECASE)
    _RE_MEMORY  = re.compile(r"\bMEMORY\s*\{", re.IGNORECASE)
    _RE_SECTIONS = re.compile(r"\bSECTIONS\s*\{", re.IGNORECASE)
    _RE_ORIGIN  = re.compile(r"ORIGIN\s*=\s*0x[0-9a-fA-F]+")
    _RE_LENGTH  = re.compile(r"LENGTH\s*=\s*[\dKkMm]+")
    _RE_BSS_START = re.compile(r"__bss_start")
    _RE_BSS_END   = re.compile(r"__bss_end")

    @classmethod
    def validate(cls, script_text: str) -> Tuple[bool, List[str]]:
        """Validate linker script text.

        Returns (is_valid, list_of_warnings).
        """
        warnings: List[str] = []
        is_valid = True

        if not cls._RE_MEMORY.search(script_text):
            warnings.append("MEMORY block not found; memory regions will not be enforced.")
        if not cls._RE_SECTIONS.search(script_text):
            warnings.append("SECTIONS block not found; no output sections defined.")
            is_valid = False
        if not cls._RE_ENTRY.search(script_text):
            warnings.append("ENTRY symbol not defined; linker may default to _start.")
        if not cls._RE_ORIGIN.search(script_text):
            warnings.append("No ORIGIN directives found; memory addresses may be wrong.")
        if not cls._RE_BSS_START.search(script_text):
            warnings.append("__bss_start symbol missing; BSS zeroing may fail at startup.")
        if not cls._RE_BSS_END.search(script_text):
            warnings.append("__bss_end symbol missing; BSS zeroing may fail at startup.")

        return is_valid, warnings

    @classmethod
    def validate_file(cls, path: str) -> Tuple[bool, List[str]]:
        """Validate a linker script file at path."""
        with open(path) as f:
            text = f.read()
        return cls.validate(text)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def register_linker_functions(runtime: Any) -> None:
    """Register linker-related functions with the NexusLang runtime (for meta-programming)."""

    runtime.register_function("linker_generate_script",
        lambda *a: get_linker_script_for_arch(a[0] if a else "x86_64"))

    runtime.register_function("linker_cortex_m_config",
        lambda *a: cortex_m_config(
            int(a[0]) if len(a) > 0 else 0x08000000,
            int(a[1]) if len(a) > 1 else 256 * 1024,
            int(a[2]) if len(a) > 2 else 0x20000000,
            int(a[3]) if len(a) > 3 else 64 * 1024,
        ).generate())

    runtime.register_function("linker_x86_config",
        lambda *a: x86_flat_config(
            int(a[0]) if len(a) > 0 else 0x00100000,
            int(a[1]) if len(a) > 1 else 512 * 1024,
            int(a[2]) if len(a) > 2 else 0x00200000,
            int(a[3]) if len(a) > 3 else 256 * 1024,
        ).generate())

    runtime.register_function("linker_riscv_config",
        lambda *a: riscv_config(
            int(a[0]) if len(a) > 0 else 0x20010000,
            int(a[1]) if len(a) > 1 else 512 * 1024,
            int(a[2]) if len(a) > 2 else 0x80000000,
            int(a[3]) if len(a) > 3 else 16 * 1024,
        ).generate())

    runtime.register_function("linker_validate_script",
        lambda *a: LinkerScriptValidator.validate_file(a[0]) if a else (False, ["no path given"]))

    runtime.register_function("linker_invoke",
        lambda *a: vars(invoke_linker(
            list(a[0]),
            str(a[1]),
            a[2] if len(a) > 2 else None,
            a[3] if len(a) > 3 else None,
            a[4] if len(a) > 4 else None,
        )))
