#!/usr/bin/env python3
"""
nlpllint - Wrapper script for easy invocation
"""
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from nlpl.cli.nlpllint import main

if __name__ == '__main__':
    sys.exit(main())
