"""
generate_error_docs.py
======================

Generates docs/7_development/error_codes_reference.md from the single source
of truth: src/nlpl/error_codes.py  (ERROR_CODES registry).

Run from project root:
    python dev_tools/generate_error_docs.py

The output file is checked into version control so it is always browsable
without running the interpreter.  Re-run whenever error_codes.py changes.
"""

import sys
import os
from pathlib import Path
from collections import defaultdict

PROJ_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJ_ROOT / "src"))

from nlpl.error_codes import ERROR_CODES, ErrorInfo  # noqa: E402

OUTPUT_PATH = PROJ_ROOT / "docs" / "7_development" / "error_codes_reference.md"

CATEGORY_ORDER = ["syntax", "name", "type", "runtime", "module"]
CATEGORY_LABELS = {
    "syntax":  "Syntax Errors (E001-E099)",
    "name":    "Name and Variable Errors (E100-E199)",
    "type":    "Type Errors (E200-E299)",
    "runtime": "Runtime Errors (E300-E399)",
    "module":  "Module and Import Errors (E400-E499)",
}


def _anchor(code: str) -> str:
    return code.lower()


def generate_toc(by_category: dict) -> str:
    lines = ["## Table of Contents", ""]
    for cat in CATEGORY_ORDER:
        if cat not in by_category:
            continue
        label = CATEGORY_LABELS.get(cat, cat.title())
        lines.append(f"- [{label}](#{label.lower().replace(' ', '-').replace('(', '').replace(')', '').replace('-', '-')})")
        for info in by_category[cat]:
            lines.append(f"  - [{info.code}: {info.title}](#{_anchor(info.code)})")
    lines.append("")
    return "\n".join(lines)


def generate_category_section(cat: str, errors: list) -> str:
    label = CATEGORY_LABELS.get(cat, cat.title() + " Errors")
    lines = [f"---", f"", f"## {label}", ""]
    for info in sorted(errors, key=lambda e: e.code):
        lines += [
            f"### {info.code}: {info.title}  {{#{_anchor(info.code)}}}",
            "",
            f"**Category:** `{info.category}`  ",
            f"**Code:** `{info.code}`",
            "",
            info.description,
            "",
        ]
        if info.common_causes:
            lines.append("**Common causes:**")
            lines.append("")
            for cause in info.common_causes:
                lines.append(f"- {cause}")
            lines.append("")
        if info.fixes:
            lines.append("**How to fix:**")
            lines.append("")
            for fix in info.fixes:
                lines.append(f"- {fix}")
            lines.append("")
        if info.doc_link:
            lines.append(f"**Documentation:** {info.doc_link}")
            lines.append("")
        lines.append("")
    return "\n".join(lines)


def generate_quick_reference_table(all_errors: list) -> str:
    lines = [
        "## Quick Reference",
        "",
        "| Code | Title | Category |",
        "|------|-------|----------|",
    ]
    for info in sorted(all_errors, key=lambda e: e.code):
        lines.append(f"| [`{info.code}`](#{_anchor(info.code)}) | {info.title} | `{info.category}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    by_category: dict = defaultdict(list)
    for info in ERROR_CODES.values():
        cat = info.category if info.category in CATEGORY_ORDER else "module"
        by_category[cat].append(info)

    all_errors = list(ERROR_CODES.values())
    total = len(all_errors)

    header = f"""\
# NLPL Error Code Reference

> **Auto-generated** from `src/nlpl/error_codes.py`.
> Do not edit this file manually — run `python dev_tools/generate_error_docs.py` to regenerate.

This document lists all {total} NLPL error codes with descriptions, common causes, and fix guidance.

Use `nlpl --explain EXXX` in the terminal (or the "NLPL: Explain Error Code" command in VS Code)
to see this information inline while coding.

"""

    toc = generate_toc(by_category)
    quick_ref = generate_quick_reference_table(all_errors)

    category_sections = "\n".join(
        generate_category_section(cat, by_category[cat])
        for cat in CATEGORY_ORDER
        if cat in by_category
    )

    footer = f"""\
---

*Generated from `src/nlpl/error_codes.py` — {total} error codes across {len(by_category)} categories.*
"""

    content = header + toc + "\n" + quick_ref + "\n" + category_sections + footer

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated: {OUTPUT_PATH}  ({total} error codes)")


if __name__ == "__main__":
    main()
